//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodLuck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Challan
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string ChallanNo { get; set; }
        public Nullable<System.DateTime> ChallanDate { get; set; }
        public string Size { get; set; }
        public string Schedule { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> C90D_Nos { get; set; }
        public Nullable<int> C90D_Length { get; set; }
        public Nullable<int> C1D_Nos { get; set; }
        public Nullable<int> C1D_Length { get; set; }
        public Nullable<int> C45D_Nos { get; set; }
        public Nullable<int> C45D_Length { get; set; }
        public Nullable<int> Long_Nos { get; set; }
        public Nullable<int> Long_Length { get; set; }
        public Nullable<int> Reducer_Nos { get; set; }
        public Nullable<int> Reducer_Length { get; set; }
        public Nullable<int> Balance_Length { get; set; }
        public Nullable<int> Scrap_Length { get; set; }
        public Nullable<System.DateTime> Scrap_Date { get; set; }
    }
}
